"""
issue_intelligence.data.audit
==============================
Stage 1B — Reusable dataset audit functions.

All functions operate on plain Python data structures (lists of dicts)
so they can be called from the CLI script, the notebook, and unit tests
without any Jupyter dependency.

No matplotlib is imported at module level. Figures are generated by
the notebook and the CLI script, which control their own backends.
"""

from __future__ import annotations

import json
import re
from collections import Counter, defaultdict
from datetime import datetime
from pathlib import Path
from typing import Any

# ---------------------------------------------------------------------------
# Constants — provisional labels (subject to revision after the audit)
# ---------------------------------------------------------------------------

# These five are our candidate issue-type prediction classes.
# They will be finalised after the Stage 1B audit.
PROVISIONAL_TYPE_LABELS: frozenset[str] = frozenset(
    ["Bug", "Documentation", "New Feature", "RFC", "Build / CI"]
)

# Prefixes that may indicate the category has leaked into the title.
LEAKAGE_PREFIXES: list[str] = [
    "BUG", "DOC", "ENH", "FEATURE", "RFC", "CI", "FIX", "MAINT", "TST",
]


# ---------------------------------------------------------------------------
# Data loading and validation
# ---------------------------------------------------------------------------


def load_issues(path: str | Path) -> list[dict[str, Any]]:
    """
    Load and validate the issues JSON file.

    Raises
    ------
    FileNotFoundError  if the file does not exist.
    ValueError         if the file is not a JSON array, or if it is empty.
    """
    path = Path(path)
    if not path.exists():
        raise FileNotFoundError(f"Issues file not found: {path}")
    with open(path, encoding="utf-8") as fh:
        data = json.load(fh)
    if not isinstance(data, list):
        raise ValueError(
            f"Expected a JSON array in {path}, got {type(data).__name__}"
        )
    if len(data) == 0:
        raise ValueError(f"Issues file is empty — nothing to audit: {path}")
    return data


def load_metadata(path: str | Path) -> dict[str, Any]:
    """Load the collection metadata JSON file."""
    path = Path(path)
    if not path.exists():
        raise FileNotFoundError(f"Metadata file not found: {path}")
    with open(path, encoding="utf-8") as fh:
        return json.load(fh)


# ---------------------------------------------------------------------------
# Label analysis
# ---------------------------------------------------------------------------


def compute_label_frequencies(issues: list[dict]) -> Counter:
    """Return a Counter mapping each label name to its occurrence count."""
    counter: Counter = Counter()
    for issue in issues:
        for label in issue.get("labels") or []:
            counter[label] += 1
    return counter


def compute_labels_per_issue(issues: list[dict]) -> list[int]:
    """Return a list of label counts, one per issue (0 if unlabelled)."""
    return [len(issue.get("labels") or []) for issue in issues]


def compute_label_cooccurrence(
    issues: list[dict],
    selected_labels: list[str] | None = None,
) -> dict[tuple[str, str], int]:
    """
    Count how often pairs of labels appear together on the same issue.

    If selected_labels is given, only pairs where both labels are in
    that set are counted.  Otherwise all labels are included.

    Returns
    -------
    A dict mapping (label_a, label_b) → count, where label_a < label_b
    lexicographically (each pair is stored once).
    """
    cooc: dict[tuple[str, str], int] = defaultdict(int)
    for issue in issues:
        labels = list(issue.get("labels") or [])
        if selected_labels is not None:
            labels = [lb for lb in labels if lb in selected_labels]
        for i in range(len(labels)):
            for j in range(i + 1, len(labels)):
                pair: tuple[str, str] = tuple(sorted([labels[i], labels[j]]))  # type: ignore[assignment]
                cooc[pair] += 1
    return dict(cooc)


def categorize_labels_provisionally(
    label_freq: Counter,
) -> dict[str, list[str]]:
    """
    Provisionally group observed labels into four roles.

    IMPORTANT: This grouping is manually proposed based on the 500-issue
    sample only.  It must be treated as provisional and will be revised
    after a broader collection.

    Categories
    ----------
    type       — What kind of issue this is (prediction target).
    component  — Which part of the codebase is affected.
    workflow   — Current triage or process state.
    lifecycle  — Administrative / housekeeping labels.
    other      — Labels not yet classified.
    """
    type_labels = ["Bug", "Documentation", "New Feature", "RFC", "Build / CI"]
    component_labels = [
        "Array API", "Callbacks", "module:test-suite", "free-threading",
        "frontend", "API", "module:linear_model",
    ]
    workflow_labels = [
        "Needs Triage", "Needs Decision", "Needs Investigation",
        "Needs Info", "Needs Decision - Include Feature",
    ]
    lifecycle_labels = ["Closing candidate", "spam", "Sprint"]

    known = set(
        type_labels + component_labels + workflow_labels + lifecycle_labels
    )
    other = [lb for lb in label_freq if lb not in known]

    return {
        "type": type_labels,
        "component": component_labels,
        "workflow": workflow_labels,
        "lifecycle": lifecycle_labels,
        "other": sorted(other),
    }


# ---------------------------------------------------------------------------
# Missing data and text quality
# ---------------------------------------------------------------------------


def compute_missing_data(issues: list[dict]) -> dict[str, int]:
    """
    Count issues with missing (None) or empty (whitespace-only) fields.

    Returns a dict with separate counts for title and body problems.
    """
    missing_title = empty_title = 0
    missing_body = empty_body = 0

    for issue in issues:
        title = issue.get("title")
        body = issue.get("body")

        if title is None:
            missing_title += 1
        elif not str(title).strip():
            empty_title += 1

        if body is None:
            missing_body += 1
        elif not str(body).strip():
            empty_body += 1

    return {
        "missing_title": missing_title,
        "empty_title": empty_title,
        "missing_body": missing_body,
        "empty_body": empty_body,
        "total_title_problems": missing_title + empty_title,
        "total_body_problems": missing_body + empty_body,
    }


def compute_text_lengths(issues: list[dict]) -> dict[str, list[int]]:
    """
    Compute character lengths for title, body, and their concatenation.

    Missing / None values are treated as empty strings (length 0).
    Trailing whitespace is stripped before measuring.
    """
    title_lengths, body_lengths, combined_lengths = [], [], []

    for issue in issues:
        title = str(issue.get("title") or "").strip()
        body = str(issue.get("body") or "").strip()
        title_lengths.append(len(title))
        body_lengths.append(len(body))
        combined_lengths.append(len(title) + len(body))

    return {
        "title": title_lengths,
        "body": body_lengths,
        "combined": combined_lengths,
    }


def describe_lengths(lengths: list[int]) -> dict[str, float]:
    """
    Return descriptive statistics for a list of integer lengths.
    Requires numpy — only call from environments where numpy is available.
    """
    import numpy as np  # lazy import: numpy is not a dep of pure audit logic

    arr = np.array(lengths, dtype=float)
    return {
        "min": float(np.min(arr)),
        "max": float(np.max(arr)),
        "mean": float(np.mean(arr)),
        "median": float(np.median(arr)),
        "p25": float(np.percentile(arr, 25)),
        "p75": float(np.percentile(arr, 75)),
        "p95": float(np.percentile(arr, 95)),
    }


# ---------------------------------------------------------------------------
# State and temporal distributions
# ---------------------------------------------------------------------------


def compute_state_distribution(issues: list[dict]) -> Counter:
    """Count issues by state ('open' or 'closed')."""
    return Counter(issue.get("state", "unknown") for issue in issues)


def compute_temporal_distribution(issues: list[dict]) -> Counter:
    """
    Count issues by year-month of creation.

    Returns a Counter keyed by 'YYYY-MM' strings, sorted chronologically.
    """
    monthly: Counter = Counter()
    for issue in issues:
        ts = issue.get("created_at")
        if ts:
            try:
                dt = datetime.fromisoformat(ts.replace("Z", "+00:00"))
                monthly[dt.strftime("%Y-%m")] += 1
            except ValueError:
                pass
    return monthly


# ---------------------------------------------------------------------------
# Leakage detection
# ---------------------------------------------------------------------------


def detect_leakage(
    issues: list[dict],
    type_labels: frozenset[str] | None = None,
    prefixes: list[str] | None = None,
) -> dict[str, list[int]]:
    """
    Check issue titles for patterns that might cause label leakage.

    Two checks are performed:

    1. Prefix check — does the title begin with a known category prefix
       such as "[BUG]", "ENH:", "RFC" etc.?
    2. Label-in-title check — does the title contain a type label name
       literally (e.g. the word "bug" in a Bug-labelled issue)?

    Returns
    -------
    A dict mapping check name → list of issue numbers that triggered it.
    """
    if type_labels is None:
        type_labels = PROVISIONAL_TYPE_LABELS
    if prefixes is None:
        prefixes = LEAKAGE_PREFIXES

    # Pattern: optional whitespace, optional [ or (, then prefix, then
    # ] or ) or : or whitespace — at the very start of the string.
    prefix_pattern = re.compile(
        r"^\s*[\[\(]?("
        + "|".join(re.escape(p) for p in prefixes)
        + r")[\]\):\s]",
        re.IGNORECASE,
    )

    prefix_matches: list[int] = []
    label_in_title: list[int] = []

    for issue in issues:
        number = issue.get("number", -1)
        title = str(issue.get("title") or "")
        title_lower = title.lower()

        if prefix_pattern.match(title):
            prefix_matches.append(number)

        # Check if any type label name appears literally in the title
        for label in type_labels:
            if label.lower() in title_lower:
                label_in_title.append(number)
                break

    return {
        "prefix_matches": prefix_matches,
        "label_in_title": label_in_title,
    }


# ---------------------------------------------------------------------------
# Provisional type-label subset
# ---------------------------------------------------------------------------


def build_provisional_subset(
    issues: list[dict],
    type_labels: frozenset[str] | None = None,
) -> dict[str, Any]:
    """
    Build the provisional single-type-label subset.

    Rules
    -----
    - An issue must have exactly ONE provisional type label to be included.
    - Issues with zero type labels are excluded (unlabelled for our task).
    - Issues with two or more type labels are excluded (ambiguous).

    Returns
    -------
    A dict containing:
    subset           : list of (issue_dict, assigned_label) pairs
    class_counts     : Counter of label → count in the subset
    excluded_unlabelled : count excluded for having no type label
    excluded_multi_type : count excluded for having multiple type labels
    total_usable     : len(subset)
    type_label_overlap : list of (issue_number, matched_labels) for multi-type issues
    """
    if type_labels is None:
        type_labels = PROVISIONAL_TYPE_LABELS

    subset: list[tuple[dict, str]] = []
    excluded_unlabelled = 0
    excluded_multi_type = 0
    type_label_overlap: list[tuple[int, list[str]]] = []

    for issue in issues:
        issue_labels = set(issue.get("labels") or [])
        type_matches = issue_labels & type_labels

        if len(type_matches) == 0:
            excluded_unlabelled += 1
        elif len(type_matches) > 1:
            excluded_multi_type += 1
            type_label_overlap.append(
                (issue.get("number", -1), sorted(type_matches))
            )
        else:
            assigned = next(iter(type_matches))
            subset.append((issue, assigned))

    class_counts: Counter = Counter(label for _, label in subset)

    return {
        "subset": subset,
        "class_counts": class_counts,
        "excluded_unlabelled": excluded_unlabelled,
        "excluded_multi_type": excluded_multi_type,
        "total_usable": len(subset),
        "type_label_overlap": type_label_overlap,
    }


# ---------------------------------------------------------------------------
# Stage 1C — yearly analysis and label scheme comparison
# ---------------------------------------------------------------------------


def compute_yearly_distribution(issues: list[dict]) -> Counter:
    """
    Count issues by year of creation.

    Returns a Counter keyed by 'YYYY' strings, sorted chronologically.
    """
    yearly: Counter = Counter()
    for issue in issues:
        ts = issue.get("created_at")
        if ts:
            try:
                dt = datetime.fromisoformat(ts.replace("Z", "+00:00"))
                yearly[dt.strftime("%Y")] += 1
            except ValueError:
                pass
    return yearly


def compute_label_distribution_by_year(
    issues: list[dict],
    labels: list[str],
) -> dict[str, Counter]:
    """
    For each year, count how many issues carry each of the given labels.

    Only issues with exactly one matching label are counted (single-type
    rule), consistent with build_provisional_subset.

    Returns
    -------
    A dict mapping year string ('YYYY') to a Counter of label → count.
    """
    by_year: dict[str, Counter] = defaultdict(Counter)
    label_set = set(labels)

    for issue in issues:
        ts = issue.get("created_at")
        if not ts:
            continue
        try:
            dt = datetime.fromisoformat(ts.replace("Z", "+00:00"))
            year = dt.strftime("%Y")
        except ValueError:
            continue

        issue_labels = set(issue.get("labels") or [])
        matches = issue_labels & label_set
        if len(matches) == 1:
            assigned = next(iter(matches))
            by_year[year][assigned] += 1

    return dict(by_year)


def build_label_scheme_stats(
    issues: list[dict],
    scheme: dict[str, list[str]],
) -> dict[str, Any]:
    """
    Compute class counts for a custom label scheme.

    A label scheme is a dict mapping a new class name to the list of
    original GitHub labels that should map to it.  For example::

        scheme = {
            "Bug":           ["Bug"],
            "Documentation": ["Documentation"],
            "Enhancement":   ["New Feature", "RFC"],
            "Infrastructure":["Build / CI"],
        }

    The single-type rule still applies: an issue must have exactly ONE
    class (after merging) to be included.  Issues whose original labels
    map to more than one scheme class are excluded as ambiguous.

    Returns
    -------
    A dict with:
      class_counts       : Counter of scheme_class → count
      total_usable       : sum of class_counts values
      excluded_unlabelled: issues with no matching scheme label
      excluded_multi_class: issues mapping to more than one scheme class
      imbalance_ratio    : max_count / min_count  (or None if < 2 classes)
      min_class_count    : minimum examples in any class
    """
    # Build reverse mapping: original_label → scheme_class
    label_to_class: dict[str, str] = {}
    for class_name, original_labels in scheme.items():
        for orig in original_labels:
            label_to_class[orig] = class_name

    class_counts: Counter = Counter()
    excluded_unlabelled = 0
    excluded_multi_class = 0

    for issue in issues:
        issue_labels = set(issue.get("labels") or [])
        assigned_classes = set()
        for lb in issue_labels:
            if lb in label_to_class:
                assigned_classes.add(label_to_class[lb])

        if len(assigned_classes) == 0:
            excluded_unlabelled += 1
        elif len(assigned_classes) > 1:
            excluded_multi_class += 1
        else:
            class_counts[next(iter(assigned_classes))] += 1

    total_usable = sum(class_counts.values())
    counts = list(class_counts.values())
    imbalance_ratio = (
        max(counts) / min(counts)
        if len(counts) >= 2 and min(counts) > 0
        else None
    )
    min_class_count = min(counts) if counts else 0

    return {
        "class_counts": class_counts,
        "total_usable": total_usable,
        "excluded_unlabelled": excluded_unlabelled,
        "excluded_multi_class": excluded_multi_class,
        "imbalance_ratio": imbalance_ratio,
        "min_class_count": min_class_count,
    }
